# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Test Project and Build & Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: NPM install
      run: cd src/main/resources/frontend/eportfolio-frontend && npm install
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build the Docker image
      run: docker build -t ombrelin/eportfolio-backend:1.0 . --file Dockerfile
    - name: Docker login
      run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login --username ombrelin --password-stdin
    - name: Publish to Docker hub
      run: docker push ombrelin/eportfolio-backend:1.0
